pkg: Fix rpm warnings about not being able to read its database
When building on many debian machines, the RPM database, by default at
/var/lib/rpm/rpmdb.sqlite, does not exist and can not be created when
running as an unprivileged user. This will cause any rpm command that
ties to access the database to print this obnoxious error message:

  error: Unable to open sqlite database /var/lib/rpm/rpmdb.sqlite: unable to open database file
  error: cannot open Packages index using sqlite - Operation not permitted (1)
  error: cannot open Packages database in /var/lib/rpm

It appears as though this doesn't cause any failures and is really a
warning. However, it can be printed more than 20 times when making the
deb-kmod target.

Detect when the database file is not readable at configure time and
setup various rpm and rpmbuild invocations to use the root of the build
directory as the database directory path. The alien program internally
runs various rpm queries, however it provides no good way to tell those
rpm invocations to use an alternate database path. A fake home is setup
in the build directory to create the user rpm macro file with the
database path defined there. Then run is alien with that home directory
so its rpm invocations will pick up the desired database path.

Reviewed-by: Brian Behlendorf <behlendorf1@llnl.gov>
Signed-off-by: Glenn Washburn <development@efficientek.com>
Closes #19162