Remove unused `zpool_is_bootable`
Otherwise compiler errors with:
```
libzfs_pool.c:449:1: error: 'zpool_is_bootable'
 defined but not used [-Werror=unused-function]
```

Signed-off-by: George Melikov <mail@gmelikov.ru>