Linux 6.6 compat: fix uninitialized timespec for LLVM
Commit fe9d409e9088 ("Linux 6.6 compat: use inode_get/set_ctime*(...)")
adds compatibility with Linux v6.6 but people using the LLVM toolchain for
their kernels encounter kabi check failure due to uninitialized `ts`:

```
/var/lib/dkms/zfs/2.2.1/build/build/inode_set_ctime_to_ts/inode_set_ctime_to_ts.c:79:30: error: variable 'ts' is uninitialized when used here [-Werror,-Wuninitialized]
   79 |                 inode_set_ctime_to_ts(&ip, ts);
      |                                            ^~
/var/lib/dkms/zfs/2.2.1/build/build/inode_set_ctime_to_ts/inode_set_ctime_to_ts.c:76:3: note: variable 'ts' is declared here
   76 |                 struct timespec64 ts;
      |                 ^
```

Similar incident was fixed with commit 3e5d41d807b0
("config/kernel-inode-times: initialize timespec").

Follow it and initialize `ts`.

Fixes: fe9d409e9088 ("Linux 6.6 compat: use inode_get/set_ctime*(...)")
Signed-off-by: Juhyung Park <qkrwngud825@gmail.com>