fix compilation error
arc.c:3470:47: error: ‘buf’ undeclared (first use in this function)
   cmn_err(CE_PANIC, "invalid arc state 0x%p", buf->b_state);

change introduced with "Illumos 5369 - arc flags should be an enum"