Linux 3.4 compat: d_make_root() replaces d_alloc_root()
torvalds/linux@adc0e91ab142abe93f5b0d7980ada8a7676231fe introduced
introduced d_make_root() as a replacement for d_alloc_root(). Further
commits appear to have removed d_alloc_root() from the Linux source
tree. This causes the following failure:

error: implicit declaration of function 'd_alloc_root'
[-Werror=implicit-function-declaration]

To correct this, we introduce an autotools check for d_alloc_root() and
use it whenever it is available.

Signed-off-by: Richard Yao <ryao@gentoo.org>