autotools: build systemd components conditionally
Needed to fix build failures on musl (where we don't
have systemd anyway):
```
zfs-mount-generator.c: In function 'line_worker':
zfs-mount-generator.c:238:24: warning: implicit declaration of function 'strndupa'; did you mean 'strndup'? [-Wimplicit-function-declaration]
  238 |                 pool = strndupa(pool, toktmp - pool);
      |                        ^~~~~~~~
      |                        strndup
zfs-mount-generator.c:238:22: warning: assignment to 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  238 |                 pool = strndupa(pool, toktmp - pool);
      |                      ^
```

Don't systemd-related files like zfs-mount-generator.c if --disable-systemd is
passed to the build system (the default behaviour has not changed).

Note that we already had this flag for installing the units conditionally.

Signed-off-by: Sam James <sam@gentoo.org>