There was a error when building zfs
issues:
zfs build

randfree_file.c: In function ‘main’:
randfree_file.c:101: error: ‘FALLOC_FL_PUNCH_HOLE’ undeclared (first use in this function)

solution:
The FALLOC_FL_PUNCH_HOLE flag was introduced in the 2.6.38 kernel. So we need add the "#if #else #endif" for older kernel.