Illumos 6171 dsl_prop_unregister() slows down dataset eviction.
Reviewed by: Matthew Ahrens <mahrens@delphix.com>
Reviewed by: Prakash Surya <prakash.surya@delphix.com>
Approved by: Dan McDonald <danmcd@omniti.com>

References:
https://www.illumos.org/issues/6171 dsl_prop_unregister() slows down dataset eviction.
https://github.com/illumos/illumos-gate/commit/03bad06fbb261fd4a7151a70dfeff2f5041cce1f#diff-832418f8bef771ab321cc8bca7235e4dL297

Porting notes:
Notable changes from upstream are caused by the following commits:
https://github.com/zfsonlinux/zfs/commit/3558fd73b5d863304102f6745c26e0b592aca60a Prototype/structure update for Linux
https://github.com/zfsonlinux/zfs/commit/2cf7f52bc42f215d4ef27d0fd75fc1b1417cb841 Linux compat 2.6.39: mount_nodev()
https://github.com/zfsonlinux/zfs/commit/13fe019870c8779bf2f5b3ff731b512cf89133ef Illumos #3464

Fix compilation error:
dsl_prop.c:1211:15: error: ‘dsl_prop_unregister’ undeclared here (not in a function)
 EXPORT_SYMBOL(dsl_prop_unregister);

Replacing
EXPORT_SYMBOL(dsl_prop_unregister);
with
EXPORT_SYMBOL(dsl_prop_unregister_all);

Fixing 'space or tab at end of line' in include/sys/dsl_dataset.h

Conflicts during rebase on December 9th 2015
in include/sys/dsl_dataset.h
due to https://github.com/zfsonlinux/zfs/commit/241b5415748859a3c272fc8f570f2368e93adde9
(Illumos 5959 - clean up per-dataset feature count code)

Ported-by: kernelOfTruth kerneloftruth@gmail.com